version: "3.4"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    networks:
      - cicd
    ports:
      - '8443:443'
      - '8082:80'
      - '8022:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

networks:
  cicd:
    external:
      name: cicd

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: