version: "3.4"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    networks:
      - cicd
    ports:
      - "8081:8081"
    volumes:
      - "nexus_data:/nexus"

  portainer:
    image: portainer/portainer
    container_name: portainer
    networks:
      - cicd
    ports:
      - '8000:8000'
      - '9001:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    networks:
      - cicd
    ports:
      - '8443:443'
      - '8082:80'
      - '8022:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

networks:
  cicd:
    external:
      name: cicd

volumes:
  nexus_data:
  portainer_data:
  gitlab_config:
  gitlab_logs:
  gitlab_data: